name: htmlize

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: |
        sudo apt update -y
        sudo apt install -y graphviz openssl fonts-wqy-microhei texlive-latex-extra
        sudo sed -i '/# deb-src.*bionic main restricted/ s/# deb-src/deb-src/' /etc/apt/sources.list
        sudo apt update
        sudo apt build-dep imagemagick
        curl -sjklL https://www.imagemagick.org/download/ImageMagick.tar.gz -o - |tar -zxf - -C /tmp
        pushd /tmp/ImageMagick-7*
        ./configure && make && sudo make install
        popd
        sudo ldconfig /usr/local/lib
        sudo snap install emacs --classic
    - name: install
      run: |
        npm install
    - name: genreate
      run: |
        npm run clean
        npm run build
    - name: deploy
      env:
        DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
      run: |
        npm run deploy
