name: htmlize

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: |
        sudo apt update -y
        sudo apt install -y graphviz openssl fonts-wqy-microhei imagemagick auctex
        sudo snap install emacs --classic
    - name: install
      run: |
        git submodule update --init
        npm install
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v2
    - name: genreate
      run: |
        npm run clean
        npm run build
    - name: deploy
      env:
        DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
      run: |
        npm run deploy
